# Generated by Django 2.1.2 on 2018-10-13 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50, null=True)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ManyToManyField(related_name='_account_parent_+', to='arbol.Account')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
