# Generated by Django 2.1.2 on 2018-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0003_auto_20181013_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='account',
            name='parent',
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ManyToManyField(related_name='_account_parent_+', to='arbol.Account'),
        ),
    ]
