# Generated by Django 2.1.2 on 2018-10-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0004_auto_20181013_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ManyToManyField(related_name='_account_parent_+', to='arbol.Account'),
        ),
    ]
